### ISSUE TITLE
Loss_region unable to converge

### ISSUE THREAD

**Issue by lu-ming-lei** [THU-DA-6D-Pose-Group/GDR-Net#11]
![1](https://user-images.githubusercontent.com/55871206/122761486-df840800-d2ce-11eb-8eb4-89148bb4d9b2.png)
Other Loss has significant decline， but Loss_region‘s drop is very weak. My training use config : configs/gdrn/lm/a6_cPnP_lm13.py
Region area choose 4, 16, 64 can not make any improve.

**Comment by wangg12** [comment]
How is your test performance?

**Comment by lu-ming-lei** [comment]
The performanceis similar to your result

**Comment by lu-ming-lei** [comment]
As shown in Paper， without using Loss_region can still work well, but I wonder why it is hard to estimate this part. I think estimate crop_xyz is a harder task and it can work.

**Comment by wangg12** [comment]
> As shown in Paper， without using Loss_region can still work well, but I wonder why it is hard to estimate this part. I think estimate crop_xyz is a harder task and it can work.

Loss region can be regarded as a regularizer or auxiliary task for learning the symmetries and the coarse region information. To estimate a 6D pose, we only need the correspondences, so the network might pay more attention to optimize towards the xyz part rather than the regions. Besides, when doing the class-agnostic training, the learning of regions might  be much harder.

**Comment by lu-ming-lei** [comment]
thanks for your explanation
