### ISSUE TITLE
关于训练lm时报共享内存不足的错

### ISSUE THREAD

**Issue by ghost** [THU-DA-6D-Pose-Group/GDR-Net#16]

**Comment by Coffee810** [comment]
请问，训练lm数据集时，在屏蔽了lm_imgn数据集，torch=1.6，cuda=10.1的条件下，
报错malloc(): memory corruption、  
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)、
RuntimeError: DataLoader worker (pid 3216) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.、
raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 3216) exited unexpectedly。
是什么原因呢？

**Comment by wangg12** [comment]
您系统的共享内存是多大？

**Comment by Junhuan-Peng** [comment]
我们目前通过重做数据集和降低batch_size暂时规避了这个问题，查到的最大共享内存是49512 bytes/block
